WebApp/graphApp/urls.py
from django.urls import path
from graphApp import views

app_name = 'graphApp'

urlpatterns = [
    path('data/', views.data, name='data'),
    path('sma/', views.sma, name='sma'),
    path('optimizedSma/', views.optimizedSma, name='optimizedSma'),
    path('MLBacktesting/', views.MLBacktesting, name='MLBacktesting'),
    path('optimalLags/', views.optimalLags, name='optimalLags')
]

WebApp/graphPlot/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from graphApp import views

urlpatterns = [
    path('', views.home, name='home'),
    path('graphApp/', include('graphApp.urls')),
    path('admin/', admin.site.urls),
]

WebApp/graphApp/models.py
from django.db import models

# Create your models here.

WebApp/graphApp/forms.py
from django import forms
from django.forms import ModelForm, widgets

class DateInput(forms.DateInput):
    input_type = 'date'

CHOICES=[('1d','1 day'),
         ('5d','5 days'),
         ('1wk','1 week'),
         ('1mo','1 month'),
         ('3mo','3 months')]

MODELS=[('Logistic Regression','Logistic Regression'),
         ('Random Forest','Random Forest')]

class DataForm(forms.Form):
    ticker = forms.CharField()
    start_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())
    
    frequency = forms.CharField(widget=forms.RadioSelect(choices=CHOICES))

class SMAForm(forms.Form):
    ticker = forms.CharField()
    start_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())
    sma_short = forms.IntegerField()
    sma_long = forms.IntegerField()

class optimizedSMAForm(forms.Form):
    ticker = forms.CharField()
    start_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())

class MLBacktestingForm(forms.Form):
    ticker = forms.CharField()
    model = forms.CharField(widget=forms.RadioSelect(choices=MODELS))
    start_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())
    lags = forms.IntegerField()
    trading_cost = forms.FloatField()

class optimalLagsForm(forms.Form):
    ticker = forms.CharField()
    model = forms.CharField(widget=forms.RadioSelect(choices=MODELS))
    start_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())
    trading_cost = forms.FloatField()

WebApp/graphApp/views.py
from statistics import mode
from django.shortcuts import render
from django.http import JsonResponse
import matplotlib.pyplot as plt
from io import StringIO
import numpy as np
import pandas as pd
from pandas.tseries.offsets import BDay
from . import forms
import yfinance as yf
from plotly.offline import plot
import plotly.express as px
from plotly.graph_objs import Scatter, Figure, Layout, Candlestick
from itertools import product
import datetime as dt
from . import backtester as MLB
# Create your views here.

def return_data(ticker, start, end, freq):
    stocks = yf.download(ticker, start=start, end=end, interval=freq)
    stocks.dropna(inplace=True)

    return [stocks.index.tolist(), stocks['Adj Close'].tolist(), stocks['Open'].tolist(),
            stocks['High'].tolist(), stocks['Low'].tolist(), stocks['Close'].tolist()]

def return_sma(ticker, start, end, short, long):
    stocks = yf.download(ticker, start=start-BDay(252), end=end)
    stocks['SMA_S'] = stocks['Adj Close'].rolling(short).mean()
    stocks['SMA_L'] = stocks['Adj Close'].rolling(long).mean()
    stocks.dropna(inplace=True)
    stocks = stocks.loc[stocks.index >= str(start)]
    return [stocks.index.tolist(), stocks['Adj Close'].tolist(),
            stocks['SMA_S'].tolist(), stocks['SMA_L'].tolist()]

def test_strategy(SMA,df):
    data = df.copy()
    data['returns'] = np.log(data.price/data.price.shift(1))
    data['SMA_S'] = data.price.rolling(int(SMA[0])).mean()
    data['SMA_L'] = data.price.rolling(int(SMA[1])).mean()
    data.dropna(inplace=True)

    data['position'] = np.where(data['SMA_S']>data['SMA_L'], 1, -1)
    data['strategy'] = data.position.shift(1)*data['returns']
    data.dropna(inplace=True)

    return np.exp(data['strategy'].sum())

def return_optimized_sma(ticker, start, end):
    stocks = yf.download(ticker, start=start, end=end)
    df = stocks.loc[:, "Close"].copy().to_frame()
    df.rename(columns = {'Close':'price'}, inplace=True)

    SMA_S_range = range(10,50,1)
    SMA_L_range = range(100,252,1)
    combinations = list(product(SMA_S_range,SMA_L_range))

    results = []
    for comb in combinations:
        results.append(test_strategy(comb,df))
        if len(results)%100 == 0:
            print(len(results))

    many_results = pd.DataFrame(data=combinations, columns=['SMA_S','SMA_L'])
    many_results['performance'] =  results
    many_results = many_results.nlargest(10, 'performance')
    return [many_results.SMA_S.tolist(), many_results.SMA_L.tolist(), many_results.performance.tolist()]

def return_ml_result(ticker, start, end, lags, tc, model):
    ml = MLB.MLBacktester(ticker, start, end, tc, model)
    perf,outperf = ml.test_strategy(train_ratio = 0.9, lags = lags)
    results = ml.get_result()
    dates = results.index.to_list()
    creturns = results.creturns.to_list()
    cstrategy = results.cstrategy.to_list()

    return perf,outperf,dates,creturns,cstrategy

def return_optimal_lags(ticker, start, end, tc, model):
    ml = MLB.MLBacktester(ticker, start, end, tc, model)
    
    lags = []
    perf = []
    outperf = []
    for l in range(1, 21):
        p,op =  ml.test_strategy(train_ratio = 0.9, lags = l)
        lags.append(l)
        perf.append(p)
        outperf.append(op)
    
    return lags,perf,outperf

#VIEWS FUNCTIONS
def home(request):
    return render(request, 'graphApp/home.html')

def data(request):
    form = forms.DataForm()
    
    context = {'form': form}

    if request.method == "POST":
        form = forms.DataForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker']
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            freq = form.cleaned_data.get("frequency")
            X,Y,Open,High,Low,Close = return_data(ticker,start,end,freq)
            return JsonResponse({'X':X,'Y':Y,'Open':Open,'High':High,'Low':Low,'Close':Close})

    return render(request, 'graphApp/data.html', context)

def sma(request):
    form = forms.SMAForm()
    context = {'form': form}

    if request.method == "POST":
        form = forms.SMAForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker']
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            short = form.cleaned_data.get("sma_short")
            long = form.cleaned_data.get("sma_long")
            X,Y,smaShort,smaLong = return_sma(ticker,start,end,short,long)
            return JsonResponse({'X':X,'Y':Y,'smaShort':smaShort,'smaLong':smaLong, 'short':short, 'long':long})

    return render(request, 'graphApp/sma.html', context)

def optimizedSma(request):
    form = forms.optimizedSMAForm()
    context = {'form': form}

    if request.method == "POST":
        form = forms.optimizedSMAForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker']
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            SMA_S,SMA_L,performance = return_optimized_sma(ticker,start,end)
            return JsonResponse({'SMA_S':SMA_S,'SMA_L':SMA_L,'performance':performance})

    return render(request, 'graphApp/optimizedSma.html', context)

def MLBacktesting(request):
    form = forms.MLBacktestingForm()
    context = {'form': form}

    if request.method == "POST":
        form = forms.MLBacktestingForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker']
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            lags = form.cleaned_data['lags']
            tc = form.cleaned_data['trading_cost']
            model = form.cleaned_data.get('model')

            perf,outperf,dates,creturns,cstrategy = return_ml_result(ticker, start, end, lags, tc, model)

            return JsonResponse({'dates':dates,'creturns':creturns,'cstrategy':cstrategy,'perf':perf,'outperf':outperf,'model':model})
    
    return render(request, 'graphApp/MLBacktesting.html', context)

def optimalLags(request):
    form = forms.optimalLagsForm()
    context = {'form': form}

    if request.method == "POST":
        form = forms.optimalLagsForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker']
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            tc = form.cleaned_data['trading_cost']
            model = form.cleaned_data.get('model')

            lags,perf,outperf = return_optimal_lags(ticker, start, end, tc, model)
            return JsonResponse({'lags':lags,'perf':perf,'outperf':outperf})

    return render(request, 'graphApp/optimalLags.html', context)

WebApp/templates/graphApp/MLBacktesting.html
<!DOCTYPE html>
{% extends "graphApp/base.html" %}
{% load static %}
    {% block title_block %}
    <title>Backtest using ML</title>
    {% endblock %}

    {% block body_block %}
    <p></p>
    <h1>Backtest using Machine Learning</h1>
    <h3><b>Lags-</b> Lags here refers to the number of previous days that are used to make the predictions.</h3>
    <p></p>
    <form action="" method="POST" id="stockform">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Train" />
    </form>
    
    <div id="plotgraph" style="width:100%;max-width:1000px;height:800px"></div>
    <script src="{% static 'javascript/scriptML.js' %}"></script>
    {% endblock %}

WebApp/templates/graphApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title_block %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'graphApp:data' %}">Visualize</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'graphApp:sma' %}">SMA</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'graphApp:optimizedSma' %}">Optimize SMA</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'graphApp:MLBacktesting' %}">Backtest using Machine Learning</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'graphApp:optimalLags' %}">Find optimal number of lags</a>
            </li>
        </ul>
    </nav>
      

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

WebApp/templates/graphApp/data.html
<!DOCTYPE html>
{% extends "graphApp/base.html" %}
{% load static %}
    {% block title_block %}
    <title>Visualize</title>
    {% endblock %}
    
    {% block body_block %}
    <h1 align='center'>Visualize</h1>
    <form action="" method="POST" id="stockform">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Plot" />
    </form>

    <div id="plotgraph" style="width:100%;max-width:1000px;height:800px"></div>
    <script src="{% static 'javascript/script.js' %}"></script>
    {% endblock %}

WebApp/templates/graphApp/home.html
<!DOCTYPE html>
{% extends "graphApp/base.html" %}
    {% block title_block %}
    <title>Home</title>
    {% endblock %}
    
    {% block body_block %}
    <h2>1. Visualize</h2>
    <p>Plot a price chart as well as a candlestick chart for any particular stock for a specified period of time using the visualization tool.</p>
    <p></p>
    <h2>2. Find optimal value for Simple Moving Average</h2>
    <p>A simple moving average (SMA) is an arithmetic moving average calculated by adding recent prices and then dividing that figure by the number of time periods in the calculation average. For example, one could add the closing price of a stock for a number of time periods and then divide this total by that same number of periods. Short-term averages respond quickly to changes in the price of the underlying security, while long-term averages are slower to react.
        <p></p>
        The trader should invest when the shorter term SMA is above the longer term SMA whereas they should go short when the shorter term SMA is below the longer term SMA.
        <p></p>
        Use the Optimize SMA tool to find the optimum value of SMA short and SMA long for any company for a specified period of time. The algorithm iterates over 4000 possible combinations of SMA long and short to find the most profitable combination.
    </p>
    <p></p>
    <h2>3. Use Machine Learning based algorithms</h2>
    <p>In machine learning, classification refers to a predictive modeling problem where a class label is predicted for a given example of input data. Some of the most commonly used classification algorithms are- Logistic Regression, Naive Bayes, Stochastic Gradient Descent, K-Nearest Neighbours, Decision Tree, Random Forest, Artificial Neural Network, and Support Vector Machine.
        <p></p>
        Use Logistic Regression or Decision Trees to predict future returns.
        </p>
    {% endblock %}

WebApp/templates/graphApp/optimalLags.html
<!DOCTYPE html>
{% extends "graphApp/base.html" %}
{% load static %}
    {% block title_block %}
    <title>Find Optimal lags</title>
    {% endblock %}

    {% block body_block %}
    <p></p>
    <h1>Find optimal number of lags</h1>
    <h3><b>Lags-</b> Lags here refers to the number of previous days that are used to make the predictions.</h3>
    <p></p>
    <form action="" method="POST" id="stockform">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Optimize" />
    </form>
    
    <p></p>
    <div id="loader" style='display: none;'>
        <h4>Please wait</h4>
    </div>
    <div id="forTable"></div>

    <script src="{% static 'javascript/scriptOLags.js' %}"></script>
    {% endblock %}

WebApp/templates/graphApp/optimizedSma.html
<!DOCTYPE html>
{% extends "graphApp/base.html" %}
{% load static %}
    {% block title_block %}
    <title>Optimized SMA</title>
    {% endblock %}

    {% block body_block %}
    <h1>Find optimum values of SMA short and SMA long</h1>
    <p></p>
    <form action="" method="POST" id="stockform">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Optimize" />
    </form>
    
    <p></p>
    <div id="loader" style='display: none;'>
        <h4>Please wait</h4>
    </div>
    <div id="forTable"></div>

    <script src="{% static 'javascript/scriptOSMA.js' %}"></script>
    {% endblock %}

WebApp/templates/graphApp/sma.html
<!DOCTYPE html>
{% extends "graphApp/base.html" %}
{% load static %}
    {% block title_block %}
    <title>SMA</title>
    {% endblock %}

    {% block body_block %}
    <h1 align='center'>Simple Moving Average</h1>
    <form action="" method="POST" id="stockform">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Plot" />
    </form>

    <div id="plotgraph" style="width:100%;max-width:1000px;height:800px"></div>
    <script src="{% static 'javascript/scriptSMA.js' %}"></script>
    {% endblock %}